language: python
python:
 - "2.7"
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install libglpk-dev swig glpk-utils
install:
  - pip install python-libsbml-experimental cython numpy scipy -f https://dl.dropboxusercontent.com/u/22461024/pypi.drosophi.la/index.html --no-index
  - pip install coveralls coverage
  - pip install -r requirements.txt
  - pip install rednose
# command to run tests
script: nosetests
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/49310b0ab7233cbe21fa
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
