language: python
sudo: false
python:
- '2.7'
- '3.4'
cache:
- pip: true
- directories:
  - cplex/
services:
- redis-server
addons:
  apt:
    packages:
    - swig
    - libzmq3-dev
    - libgmp-dev
    - libglp
    - libglpk-dev
    - glpk-utils
    - pandoc
    - openbabel
before_install:
#- if [ ! -d "cplex/python/$TRAVIS_PYTHON_VERSION/x86-64_linux/" ]; then curl -L SECRET_CPLEX_LINK -o cplex.tar.gz && tar xvf cplex.tar.gz; fi
- pip install pip --upgrade
- pip install codecov
- curl -L $SECRET_CPLEX_LINK -o cplex.tar.gz
- tar xvf cplex.tar.gz
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then cd "cplex/python/3.4/x86-64_linux/"; fi
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then cd "cplex/python/2.6/x86-64_linux/"; fi
- pip install .
- cd $TRAVIS_BUILD_DIR
install:
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install pyzmq pandas; fi
- pip install numpy scipy pyzmq pandas -f http://nikosonnensche.in/wheels/index.html --trusted-host nikosonnensche.in
  --no-index
- pip install ipython[all]
- pip install ipyparallel ipywidgets
- pip install coverage
- pip install pypandoc
- pip install redis
- pip install rednose
- pip install flake8
- pip install cobra==0.4.0b6 --pre
- pip install swiglpk
- pip install .
- pip uninstall optlang -y
- pip install -e git://github.com/biosustain/optlang.git@transactions#egg=optlang
before_script:
- "flake8 ."
script: nosetests
after_success:
- codecov
notifications:
  slack: biosustain:UGm09rOjMCgXko3rS3wUivoX
before_deploy:
  - pip install twine
deploy:
  provider: pypi
  user: Nikolaus.Sonnenschein
  password:
    secure: nxjszXtUzQfnLlfg0cmFjd9gRekXDog6dkkN1rMc7CIWH2gZ1gAX4sNETVChnuSmu9egzhuIkviHstRrdyGoEZ7ZkHlTXmpVAs9AY96eMSejnwHHODhYno0jB7DjGcfejodLF+lo6lWz7S7mXXwML6YLM3xxG+AOjLHlHbPTaKc=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    repo: biosustain/cameo
  docs_dir: docs/_build/html
env:
  global:
    secure: QgrOXEgpcH6xgToVfWIX6j6CPvycKMPtNnoYAxPrZjkMzd2aCHHeokv0FZkCn3uePO0I8W8TkKBxilGZbWYoseDq+Snds18sBTG9u2NHvYHnDQb4Oki7+NoxhlnGIOj/8ADONOpc0n7PyFDPK8zmKVZvv9p78OHZO5CmV/ktOeg=
