language: python
python:
 - "2.7"
 - "3.4"
before_install:
  - sudo apt-get install swig redis-server libzmq3-dev libgmp-dev libglpk-dev glpk-utils pandoc
  - sudo service redis-server start
  - sudo rm -rf /dev/shm
  - wget https://ftp.gnu.org/gnu/glpk/glpk-4.45.tar.gz
  - tar xvf glpk-4.45.tar.gz
  - mkdir glpk
  - cd glpk-4.45
  - ./configure --prefix=/
  - make
  - sudo make install
  - cd ..
  - sudo ldconfig
  - sudo ln -s /run/shm /dev/shm
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install pyzmq pandas; fi
  - pip install python-libsbml-experimental numpy scipy pyzmq pandas -f http://nikosonnensche.in/wheels/index.html --no-index
  - pip install coveralls coverage
  - pip install pypandoc
  - pip install redis
  - pip install rednose
  # temporarily use development version of cobrapy (until 0.4 is released); cython>=0.21 needed for that
  - pip install cython>=0.21
  - pip install git+https://github.com/opencobra/cobrapy.git@095d664cbbb69fcb7ae56da997240b35ea5ddb19#egg=cobra
  - pip install .
# command to run tests
script: nosetests
after_success:
  - coveralls
notifications:
  slack: biosustain:UGm09rOjMCgXko3rS3wUivoX
deploy:
  provider: pypi
  user: Nikolaus.Sonnenschein
  password:
    secure: nxjszXtUzQfnLlfg0cmFjd9gRekXDog6dkkN1rMc7CIWH2gZ1gAX4sNETVChnuSmu9egzhuIkviHstRrdyGoEZ7ZkHlTXmpVAs9AY96eMSejnwHHODhYno0jB7DjGcfejodLF+lo6lWz7S7mXXwML6YLM3xxG+AOjLHlHbPTaKc=
  distributions: "sdist bdist_wheel" # Your distributions here
  on:
    tags: true
    repo: biosustain/cameo
